- name: Build and Push to Master
  hosts: localhost
  tasks:
    - name: Build
      shell: |
          cd ../src
          yarn build

    - name: Push to master
      shell: |
          cd ../src
          git add .
          git ci -m "Deploy"
          git push


